#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


mysql_ready() {
python << END
import sys

import pymysql
import pymysql.cursors

try:
    connection = pymysql.connect(
        host="${MYSQL_HOST}",
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        db="${MYSQL_DATABASE}",
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor
    )
except pymysql.err.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo "Waiting for MySQL to become available..."
  sleep 1
done
>&2 echo "MySQL is available"

exec "$@"
