#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


postgres_ready() {
python << END
import sys

import asyncpg
import asyncio

try:

    await asyncpg.create_pool(
            user=${POSTGRES_USER},
            password=${POSTGRES_PASSWORD},
            database=${POSTGRES_DB},
            host=${POSTGERS_HOST},
            port=${POSTGERS_PORT})
except Exception:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo "Waiting for postgres to become available..."
  sleep 1
done
>&2 echo "postgres is available"

# init postgres db schema
python init_postgres_schema.py

exec "$@"
