#!/bin/sh

set -o errexit
set -o nounset


celery flower \
    --app=celery_app.celery_app \
    --broker="redis://:${REDIS_PASSWD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
